export const BANK_CATALOG: Record<string, { name: string; code: string }> = {
  'adityabirla': { name: 'Aditya Birla Finance', code: 'ABFL' },
  'axis bank': { name: 'Axis Bank', code: 'AXIS' },
  'axis finance': { name: 'Axis Finance', code: 'AFL' },
  'bajaj finserv': { name: 'Bajaj Finserv', code: 'BAJAJ_FINSERV' },
  'bajaj markets': { name: 'Bajaj Markets', code: 'BAJAJ_MARKETS' },
  'bandhan bank': { name: 'Bandhan Bank', code: 'BANDHAN' },
  'chola': { name: 'Cholamandalam Investment & Finance', code: 'CHOLA' },
  'fibe': { name: 'Fibe (EarlySalary)', code: 'FIBE' },
  'finnable': { name: 'Finnable Credit', code: 'FINNABLE' },
  'hdfc': { name: 'HDFC Bank', code: 'HDFC' },
  'home loan': { name: 'Home Loan Services', code: 'HOME_LOAN' },
  'icici': { name: 'ICICI Bank', code: 'ICICI' },
  'idfc': { name: 'IDFC FIRST Bank', code: 'IDFC' },
  'indusind': { name: 'IndusInd Bank', code: 'INDUSIND' },
  'kotak': { name: 'Kotak Mahindra Bank', code: 'KOTAK' },
  'l& t finance': { name: 'L&T Finance', code: 'LTF' },
  'l&t finance': { name: 'L&T Finance', code: 'LTF' },
  'piramal': { name: 'Piramal Capital & Housing Finance', code: 'PIRAMAL' },
  'poonawalla': { name: 'Poonawalla Fincorp', code: 'POONAWALLA' },
  'sbm bank': { name: 'SBM Bank India', code: 'SBM' },
  'smfg': { name: 'SMFG India Credit (Fullerton)', code: 'SMFG' },
  'tata capital': { name: 'Tata Capital', code: 'TATA_CAPITAL' },
  'utkarsh small finance bank': { name: 'Utkarsh Small Finance Bank', code: 'UTKARSH' },
  'yes bank': { name: 'Yes Bank', code: 'YES_BANK' },
};
